# This file was generated by GoReleaser. DO NOT EDIT.
class Yak < Formula
  desc "A tool to log in to AWS through Okta"
  homepage "https://github.com/redbubble/yak"
  version "1.5.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/redbubble/yak/releases/download/v1.5.4/yak_1.5.4_darwin_amd64.tar.gz"
    sha256 "6089b454845d4f61efab68eb255bc73bc2a5aa694929abaadb02f0a8d5179ca2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/yak/releases/download/v1.5.4/yak_1.5.4_linux_amd64.tar.gz"
      sha256 "bd213fab494fbe5b45f1f1b46e278e259be714552dce8a1d91955b6e7d12d62b"
    end
  end

  def install
    bin.install "yak"
    bash_completion.install "static/completions/yak.bash" => "yak"
    zsh_completion.install "static/completions/yak.zsh" => "_yak"
  end

  test do
    system "#{bin}/yak --help"
  end
end
