# This file was generated by GoReleaser. DO NOT EDIT.
class Yak < Formula
  desc "A tool to log in to AWS through Okta"
  homepage "https://github.com/redbubble/yak"
  version "1.5.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/redbubble/yak/releases/download/v1.5.5/yak_1.5.5_darwin_amd64.tar.gz"
    sha256 "10e175c0f5f48b7eb404d7c6e2b243f09bddf1c23d9ff609433ae944687b3a15"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/yak/releases/download/v1.5.5/yak_1.5.5_linux_amd64.tar.gz"
      sha256 "372b361de0e1fecf21fac88aec54d8182427df503945e14f5b28c7364687a4a4"
    end
  end

  def install
    bin.install "yak"
    bash_completion.install "static/completions/yak.bash" => "yak"
    zsh_completion.install "static/completions/yak.zsh" => "_yak"
  end

  test do
    system "#{bin}/yak --help"
  end
end
