# This file was generated by GoReleaser. DO NOT EDIT.
class Yak < Formula
  desc "A tool to log in to AWS through Okta"
  homepage "https://github.com/redbubble/yak"
  version "1.5.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/redbubble/yak/releases/download/v1.5.5/yak_1.5.5_darwin_amd64.tar.gz"
    sha256 "2ee7b828c967184cba6f4793b4fa1af3cb0ff7337d081181d1beb3f730e87457"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/yak/releases/download/v1.5.5/yak_1.5.5_linux_amd64.tar.gz"
      sha256 "65eb01b69d52e78c38965a94bd61b2497c0dea4e06db5995be331f1136a9f96b"
    end
  end

  def install
    bin.install "yak"
    bash_completion.install "static/completions/yak.bash" => "yak"
    zsh_completion.install "static/completions/yak.zsh" => "_yak"
  end

  test do
    system "#{bin}/yak --help"
  end
end
